name: Ecovacs

on:
  push:
    branches: [main, dev]
    # paths:
    # - "src/debian/changelog"
    # paths-ignore:
      # - "**/changelog"
      # - "**.md"
  pull_request:
    branches: [main, dev]
    # paths:
    # - "src/debian/changelog"
    # paths-ignore:
      # - "**/changelog"
      # - "**.md"
  workflow_dispatch:
jobs:
  package-build:
    runs-on: ${{matrix.operating-system}}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        # operating-system: [ubuntu-22.04]
        # operating-system: [ubuntu-22.04, ubuntu-20.04, ubuntu-latest, ubuntu-18.04]
        # operating-system: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
