name: Ecovacs

on:
  push:
    branches: [main, dev]
    # paths:
    # - "src/debian/changelog"
    # paths-ignore:
      # - "**/changelog"
      # - "**.md"
  pull_request:
    branches: [main, dev]
    # paths:
    # - "src/debian/changelog"
    # paths-ignore:
      # - "**/changelog"
      # - "**.md"
  workflow_dispatch:
jobs:
  package-build:
    runs-on: ${{matrix.operating-system}}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        # operating-system: [ubuntu-22.04]
        # operating-system: [ubuntu-22.04, ubuntu-20.04, ubuntu-latest, ubuntu-18.04]
        # operating-system: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Pull source from home-assistant-core
        run: |
          git clone --depth 1 https://github.com/diepxuan-home-assistant/home-assistant-core temp-core

      - name: Copy ecovacs component into current repo
        run: |
          rm -rf homeassistant/components/ecovacs
          mkdir -p homeassistant/components
          cp -r temp-core/homeassistant/components/ecovacs/* ./

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: sync ecovacs component from home-assistant-core"
            git push origin ${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi
